// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/house/repository.go
//
// Generated by this command:
//
//	mockgen -source internal/repository/house/repository.go -destination internal/repository/house/repository_mock.go
//

// Package mock_houserepository is a generated GoMock package.
package houserepository

import (
	model "avito/internal/model"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CloseConnection mocks base method.
func (m *MockRepository) CloseConnection() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseConnection")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseConnection indicates an expected call of CloseConnection.
func (mr *MockRepositoryMockRecorder) CloseConnection() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseConnection", reflect.TypeOf((*MockRepository)(nil).CloseConnection))
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, house model.House) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, house)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, house any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, house)
}

// Houses mocks base method.
func (m *MockRepository) Houses(ctx context.Context, offset, limit int) ([]model.House, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Houses", ctx, offset, limit)
	ret0, _ := ret[0].([]model.House)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Houses indicates an expected call of Houses.
func (mr *MockRepositoryMockRecorder) Houses(ctx, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Houses", reflect.TypeOf((*MockRepository)(nil).Houses), ctx, offset, limit)
}
