// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/apartment/repository.go
//
// Generated by this command:
//
//	mockgen -source internal/repository/apartment/repository.go -destination internal/repository/apartment/repository_mock.go
//

// Package mock_apartmentrepository is a generated GoMock package.
package apartmentrepository

import (
	model "avito/internal/model"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Apartments mocks base method.
func (m *MockRepository) Apartments(ctx context.Context, houseID uint32, offset, limit int, moderationStatusConstraint bool) ([]model.Apartment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Apartments", ctx, houseID, offset, limit, moderationStatusConstraint)
	ret0, _ := ret[0].([]model.Apartment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Apartments indicates an expected call of Apartments.
func (mr *MockRepositoryMockRecorder) Apartments(ctx, houseID, offset, limit, moderationStatusConstraint any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Apartments", reflect.TypeOf((*MockRepository)(nil).Apartments), ctx, houseID, offset, limit, moderationStatusConstraint)
}

// CloseConnection mocks base method.
func (m *MockRepository) CloseConnection() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseConnection")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseConnection indicates an expected call of CloseConnection.
func (mr *MockRepositoryMockRecorder) CloseConnection() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseConnection", reflect.TypeOf((*MockRepository)(nil).CloseConnection))
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, apartment model.Apartment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, apartment)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, apartment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, apartment)
}

// Update mocks base method.
func (m *MockRepository) Update(ctx context.Context, apartment model.Apartment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, apartment)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRepositoryMockRecorder) Update(ctx, apartment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRepository)(nil).Update), ctx, apartment)
}
